let standingsData = {
  filters: {},
  competition: {
    id: 2014,
    area: {
      id: 2224,
      name: "Spain",
    },
    name: "Primera Division",
    code: "PD",
    plan: "TIER_ONE",
    lastUpdated: "2022-03-20T09:20:08Z",
  },
  season: {
    id: 1504,
    startDate: "2022-08-14",
    endDate: "2023-06-04",
    currentMatchday: 19,
    winner: null,
  },
  standings: [
    {
      stage: "REGULAR_SEASON",
      type: "TOTAL",
      group: null,
      table: [
        {
          position: 1,
          team: {
            id: 81,
            name: "FC Barcelona",
            crestUrl: "https://crests.football-data.org/81.svg",
          },
          playedGames: 18,
          form: null,
          won: 15,
          draw: 2,
          lost: 1,
          points: 47,
          goalsFor: 37,
          goalsAgainst: 6,
          goalDifference: 31,
        },
        {
          position: 2,
          team: {
            id: 86,
            name: "Real Madrid CF",
            crestUrl: "https://crests.football-data.org/86.png",
          },
          playedGames: 18,
          form: null,
          won: 13,
          draw: 3,
          lost: 2,
          points: 42,
          goalsFor: 38,
          goalsAgainst: 16,
          goalDifference: 22,
        },
        {
          position: 3,
          team: {
            id: 92,
            name: "Real Sociedad de Fútbol",
            crestUrl: "https://crests.football-data.org/92.svg",
          },
          playedGames: 19,
          form: null,
          won: 12,
          draw: 3,
          lost: 4,
          points: 39,
          goalsFor: 28,
          goalsAgainst: 18,
          goalDifference: 10,
        },
        {
          position: 4,
          team: {
            id: 78,
            name: "Club Atlético de Madrid",
            crestUrl: "https://crests.football-data.org/78.svg",
          },
          playedGames: 19,
          form: null,
          won: 10,
          draw: 4,
          lost: 5,
          points: 34,
          goalsFor: 28,
          goalsAgainst: 16,
          goalDifference: 12,
        },
        {
          position: 5,
          team: {
            id: 94,
            name: "Villarreal CF",
            crestUrl: "https://crests.football-data.org/94.png",
          },
          playedGames: 18,
          form: null,
          won: 9,
          draw: 4,
          lost: 5,
          points: 31,
          goalsFor: 21,
          goalsAgainst: 13,
          goalDifference: 8,
        },
        {
          position: 6,
          team: {
            id: 90,
            name: "Real Betis Balompié",
            crestUrl: "https://crests.football-data.org/90.png",
          },
          playedGames: 18,
          form: null,
          won: 9,
          draw: 4,
          lost: 5,
          points: 31,
          goalsFor: 20,
          goalsAgainst: 14,
          goalDifference: 6,
        },
        {
          position: 7,
          team: {
            id: 79,
            name: "CA Osasuna",
            crestUrl: "https://crests.football-data.org/79.svg",
          },
          playedGames: 19,
          form: null,
          won: 8,
          draw: 4,
          lost: 7,
          points: 28,
          goalsFor: 18,
          goalsAgainst: 18,
          goalDifference: 0,
        },
        {
          position: 8,
          team: {
            id: 77,
            name: "Athletic Club",
            crestUrl: "https://crests.football-data.org/77.png",
          },
          playedGames: 19,
          form: null,
          won: 7,
          draw: 5,
          lost: 7,
          points: 26,
          goalsFor: 25,
          goalsAgainst: 20,
          goalDifference: 5,
        },
        {
          position: 9,
          team: {
            id: 87,
            name: "Rayo Vallecano de Madrid",
            crestUrl: "https://crests.football-data.org/87.svg",
          },
          playedGames: 18,
          form: null,
          won: 7,
          draw: 5,
          lost: 6,
          points: 26,
          goalsFor: 24,
          goalsAgainst: 22,
          goalDifference: 2,
        },
        {
          position: 10,
          team: {
            id: 89,
            name: "RCD Mallorca",
            crestUrl: "https://crests.football-data.org/89.png",
          },
          playedGames: 19,
          form: null,
          won: 7,
          draw: 4,
          lost: 8,
          points: 25,
          goalsFor: 15,
          goalsAgainst: 18,
          goalDifference: -3,
        },
        {
          position: 11,
          team: {
            id: 267,
            name: "UD Almería",
            crestUrl: "https://crests.football-data.org/267.png",
          },
          playedGames: 19,
          form: null,
          won: 6,
          draw: 4,
          lost: 9,
          points: 22,
          goalsFor: 23,
          goalsAgainst: 29,
          goalDifference: -6,
        },
        {
          position: 12,
          team: {
            id: 298,
            name: "Girona FC",
            crestUrl: "https://crests.football-data.org/298.png",
          },
          playedGames: 19,
          form: null,
          won: 5,
          draw: 6,
          lost: 8,
          points: 21,
          goalsFor: 26,
          goalsAgainst: 29,
          goalDifference: -3,
        },
        {
          position: 13,
          team: {
            id: 559,
            name: "Sevilla FC",
            crestUrl: "https://crests.football-data.org/559.svg",
          },
          playedGames: 19,
          form: null,
          won: 5,
          draw: 6,
          lost: 8,
          points: 21,
          goalsFor: 21,
          goalsAgainst: 26,
          goalDifference: -5,
        },
        {
          position: 14,
          team: {
            id: 95,
            name: "Valencia CF",
            crestUrl: "https://crests.football-data.org/95.svg",
          },
          playedGames: 18,
          form: null,
          won: 5,
          draw: 5,
          lost: 8,
          points: 20,
          goalsFor: 25,
          goalsAgainst: 21,
          goalDifference: 4,
        },
        {
          position: 15,
          team: {
            id: 80,
            name: "RCD Espanyol de Barcelona",
            crestUrl: "https://crests.football-data.org/80.svg",
          },
          playedGames: 19,
          form: null,
          won: 4,
          draw: 8,
          lost: 7,
          points: 20,
          goalsFor: 23,
          goalsAgainst: 29,
          goalDifference: -6,
        },
        {
          position: 16,
          team: {
            id: 558,
            name: "RC Celta de Vigo",
            crestUrl: "https://crests.football-data.org/558.svg",
          },
          playedGames: 19,
          form: null,
          won: 5,
          draw: 5,
          lost: 9,
          points: 20,
          goalsFor: 18,
          goalsAgainst: 29,
          goalDifference: -11,
        },
        {
          position: 17,
          team: {
            id: 250,
            name: "Real Valladolid CF",
            crestUrl: "https://crests.football-data.org/250.png",
          },
          playedGames: 19,
          form: null,
          won: 6,
          draw: 2,
          lost: 11,
          points: 20,
          goalsFor: 14,
          goalsAgainst: 28,
          goalDifference: -14,
        },
        {
          position: 18,
          team: {
            id: 264,
            name: "Cádiz CF",
            crestUrl: "https://crests.football-data.org/264.png",
          },
          playedGames: 19,
          form: null,
          won: 4,
          draw: 7,
          lost: 8,
          points: 19,
          goalsFor: 14,
          goalsAgainst: 29,
          goalDifference: -15,
        },
        {
          position: 19,
          team: {
            id: 82,
            name: "Getafe CF",
            crestUrl: "https://crests.football-data.org/82.png",
          },
          playedGames: 19,
          form: null,
          won: 4,
          draw: 5,
          lost: 10,
          points: 17,
          goalsFor: 16,
          goalsAgainst: 26,
          goalDifference: -10,
        },
        {
          position: 20,
          team: {
            id: 285,
            name: "Elche CF",
            crestUrl: "https://crests.football-data.org/285.png",
          },
          playedGames: 19,
          form: null,
          won: 0,
          draw: 6,
          lost: 13,
          points: 6,
          goalsFor: 12,
          goalsAgainst: 39,
          goalDifference: -27,
        },
      ],
    },
  ],
};
