let standFrancesa = {
  filters: {},
  competition: {
    id: 2015,
    area: { id: 2081, name: "France" },
    name: "Ligue 1",
    code: "FL1",
    plan: "TIER_ONE",
    lastUpdated: "2022-03-20T09:30:02Z",
  },
  season: {
    id: 1497,
    startDate: "2022-08-07",
    endDate: "2023-06-03",
    currentMatchday: 24,
    winner: null,
  },
  standings: [
    {
      stage: "REGULAR_SEASON",
      type: "TOTAL",
      group: null,
      table: [
        {
          position: 1,
          team: {
            id: 524,
            name: "Paris Saint-Germain FC",
            crestUrl: "https://crests.football-data.org/524.png",
          },
          playedGames: 24,
          form: null,
          won: 18,
          draw: 3,
          lost: 3,
          points: 57,
          goalsFor: 59,
          goalsAgainst: 23,
          goalDifference: 36,
        },
        {
          position: 2,
          team: {
            id: 516,
            name: "Olympique de Marseille",
            crestUrl: "https://crests.football-data.org/516.png",
          },
          playedGames: 24,
          form: null,
          won: 16,
          draw: 4,
          lost: 4,
          points: 52,
          goalsFor: 48,
          goalsAgainst: 22,
          goalDifference: 26,
        },
        {
          position: 3,
          team: {
            id: 548,
            name: "AS Monaco FC",
            crestUrl: "https://crests.football-data.org/548.png",
          },
          playedGames: 24,
          form: null,
          won: 15,
          draw: 5,
          lost: 4,
          points: 50,
          goalsFor: 53,
          goalsAgainst: 31,
          goalDifference: 22,
        },
        {
          position: 4,
          team: {
            id: 546,
            name: "Racing Club de Lens",
            crestUrl: "https://crests.football-data.org/546.png",
          },
          playedGames: 24,
          form: null,
          won: 14,
          draw: 7,
          lost: 3,
          points: 49,
          goalsFor: 38,
          goalsAgainst: 19,
          goalDifference: 19,
        },
        {
          position: 5,
          team: {
            id: 529,
            name: "Stade Rennais FC 1901",
            crestUrl: "https://crests.football-data.org/529.png",
          },
          playedGames: 24,
          form: null,
          won: 13,
          draw: 4,
          lost: 7,
          points: 43,
          goalsFor: 44,
          goalsAgainst: 28,
          goalDifference: 16,
        },
        {
          position: 6,
          team: {
            id: 521,
            name: "Lille OSC",
            crestUrl: "https://crests.football-data.org/521.svg",
          },
          playedGames: 24,
          form: null,
          won: 12,
          draw: 5,
          lost: 7,
          points: 41,
          goalsFor: 43,
          goalsAgainst: 31,
          goalDifference: 12,
        },
        {
          position: 7,
          team: {
            id: 525,
            name: "FC Lorient",
            crestUrl: "https://crests.football-data.org/525.png",
          },
          playedGames: 24,
          form: null,
          won: 11,
          draw: 6,
          lost: 7,
          points: 39,
          goalsFor: 38,
          goalsAgainst: 35,
          goalDifference: 3,
        },
        {
          position: 8,
          team: {
            id: 522,
            name: "OGC Nice",
            crestUrl: "https://crests.football-data.org/522.png",
          },
          playedGames: 24,
          form: null,
          won: 10,
          draw: 8,
          lost: 6,
          points: 38,
          goalsFor: 30,
          goalsAgainst: 21,
          goalDifference: 9,
        },
        {
          position: 9,
          team: {
            id: 523,
            name: "Olympique Lyonnais",
            crestUrl: "https://crests.football-data.org/523.svg",
          },
          playedGames: 24,
          form: null,
          won: 10,
          draw: 5,
          lost: 9,
          points: 35,
          goalsFor: 36,
          goalsAgainst: 27,
          goalDifference: 9,
        },
        {
          position: 10,
          team: {
            id: 547,
            name: "Stade de Reims",
            crestUrl: "https://crests.football-data.org/547.png",
          },
          playedGames: 24,
          form: null,
          won: 7,
          draw: 13,
          lost: 4,
          points: 34,
          goalsFor: 30,
          goalsAgainst: 26,
          goalDifference: 4,
        },
        {
          position: 11,
          team: {
            id: 511,
            name: "Toulouse FC",
            crestUrl: "https://crests.football-data.org/511.png",
          },
          playedGames: 24,
          form: null,
          won: 9,
          draw: 5,
          lost: 10,
          points: 32,
          goalsFor: 41,
          goalsAgainst: 42,
          goalDifference: -1,
        },
        {
          position: 12,
          team: {
            id: 541,
            name: "Clermont Foot 63",
            crestUrl: "https://crests.football-data.org/541.svg",
          },
          playedGames: 24,
          form: null,
          won: 8,
          draw: 6,
          lost: 10,
          points: 30,
          goalsFor: 24,
          goalsAgainst: 33,
          goalDifference: -9,
        },
        {
          position: 13,
          team: {
            id: 543,
            name: "FC Nantes",
            crestUrl: "https://crests.football-data.org/543.svg",
          },
          playedGames: 24,
          form: null,
          won: 6,
          draw: 10,
          lost: 8,
          points: 28,
          goalsFor: 25,
          goalsAgainst: 29,
          goalDifference: -4,
        },
        {
          position: 14,
          team: {
            id: 518,
            name: "Montpellier HSC",
            crestUrl: "https://crests.football-data.org/518.png",
          },
          playedGames: 24,
          form: null,
          won: 8,
          draw: 2,
          lost: 14,
          points: 26,
          goalsFor: 35,
          goalsAgainst: 45,
          goalDifference: -10,
        },
        {
          position: 15,
          team: {
            id: 576,
            name: "RC Strasbourg Alsace",
            crestUrl: "https://crests.football-data.org/576.png",
          },
          playedGames: 24,
          form: null,
          won: 4,
          draw: 9,
          lost: 11,
          points: 21,
          goalsFor: 29,
          goalsAgainst: 42,
          goalDifference: -13,
        },
        {
          position: 16,
          team: {
            id: 512,
            name: "Stade Brestois 29",
            crestUrl: "https://crests.football-data.org/512.png",
          },
          playedGames: 24,
          form: null,
          won: 4,
          draw: 8,
          lost: 12,
          points: 20,
          goalsFor: 25,
          goalsAgainst: 40,
          goalDifference: -15,
        },
        {
          position: 17,
          team: {
            id: 531,
            name: "ES Troyes AC",
            crestUrl: "https://crests.football-data.org/531.svg",
          },
          playedGames: 24,
          form: null,
          won: 4,
          draw: 7,
          lost: 13,
          points: 19,
          goalsFor: 33,
          goalsAgainst: 53,
          goalDifference: -20,
        },
        {
          position: 18,
          team: {
            id: 519,
            name: "AJ Auxerre",
            crestUrl: "https://crests.football-data.org/519.png",
          },
          playedGames: 24,
          form: null,
          won: 4,
          draw: 6,
          lost: 14,
          points: 18,
          goalsFor: 21,
          goalsAgainst: 48,
          goalDifference: -27,
        },
        {
          position: 19,
          team: {
            id: 510,
            name: "AC Ajaccio",
            crestUrl: "https://crests.football-data.org/510.png",
          },
          playedGames: 24,
          form: null,
          won: 5,
          draw: 3,
          lost: 16,
          points: 18,
          goalsFor: 18,
          goalsAgainst: 45,
          goalDifference: -27,
        },
        {
          position: 20,
          team: {
            id: 532,
            name: "Angers SCO",
            crestUrl: "https://crests.football-data.org/532.svg",
          },
          playedGames: 24,
          form: null,
          won: 2,
          draw: 4,
          lost: 18,
          points: 10,
          goalsFor: 20,
          goalsAgainst: 50,
          goalDifference: -30,
        },
      ],
    },
  ],
};
